name: clipzyme
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip: 
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.0.1+cu118
      - rdkit
      - numpy==1.26.0
      - pandas==2.1.1
      - scikit-learn==1.3.2
      - scipy==1.11.2
      - tqdm==4.62.3
      - GitPython==3.1.27
      - comet-ml==3.28.1
      - wandb==0.12.19
      - pytorch-lightning==2.0.9
      - torchmetrics==0.11.4
      - bioservices==1.9.0
      - pubchempy==1.0.4
      - openpyxl==3.0.10      
      - transformers==4.25.1
      - rxn-chem-utils==1.0.4
      - rxn-utils==1.1.3
      - biopython==1.83
      - p_tqdm
      - einops==0.7.0
      - ninja==1.11.1.1
      - molvs==0.1.1
      - epam-indigo==1.9.0
      - fair-esm==2.0.0
      - torch-geometric==2.3.1
      - --find-links https://data.pyg.org/whl/torch-2.0.1+cu118.html 
      - pyg-lib==0.4.0+pt20cu118
      - torch-scatter==2.1.2+pt20cu118
      - torch-sparse==0.6.18+pt20cu118
      - torch-cluster==1.6.3+pt20cu118
      - torch-spline-conv==1.2.2+pt20cu118
